run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - services/store/sqlstore/migrations

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 180
  dupl:
    threshold: 200
  revive:
    enableAllRules: true
    rules:
      - name: exported
        disabled: true

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - ineffassign
    - unparam
    - errcheck
    - govet
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gosec
    - makezero
    - staticcheck
    - prealloc
    - asciicheck
    - dogsled
    - dupl
    - goconst
    - gocritic
    - godot
    - err113
    - goheader
    - revive
    - nakedret
    - gomodguard
    - goprintffuncname
    - gosimple
    - lll
    - misspell
    - nolintlint
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - gocyclo
