name: Check-in tests

on:
  push:
    branches:
      - 'main'
      - 'releases-**'
  pull_request:
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:

  ci-ubuntu-server:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        db:
          - sqlite
          - mysql
          - mariadb
          - postgres

    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version-file: server/go.mod

    - name: "Test server: ${{matrix['db']}}"
      run: make server-test-${{matrix['db']}}

  ci-ubuntu-webapp:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        path: "focalboard"
        
    - name: npm ci
      run: cd focalboard/webapp && npm ci && cd -

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version-file: focalboard/server/go.mod

    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
      with:
        node-version-file: focalboard/webapp/.nvmrc

    - name: Build Linux server
      run: cd focalboard; make server-linux-package

    - name: Copy server binary for Cypress
      run: cp focalboard/bin/linux/focalboard-server focalboard/bin/

    - name: Upload server package
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: focalboard-server-linux-amd64.tar.gz
        path: ${{ github.workspace }}/focalboard/dist/focalboard-server-linux-amd64.tar.gz

    - name: Lint & test webapp
      run: cd focalboard; make webapp-ci

  ci-windows-server:
    runs-on: windows-2022

    strategy:
      matrix:
        db:
          - sqlite

    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        path: "focalboard"

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version-file: focalboard/server/go.mod

    - name: "Test server (minimum): ${{matrix['db']}}"
      run: cd focalboard; make server-test-mini-${{matrix['db']}}

  ci-mac-server:
    runs-on: macos-15

    strategy:
      matrix:
        db:
          - sqlite

    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        path: "focalboard"

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      with:
        go-version-file: focalboard/server/go.mod

    - name: "Test server (minimum): ${{matrix['db']}}"
      run: cd focalboard; make server-test-mini-${{matrix['db']}}
