name: Check-in tests

on:
  push:
    branches:
      - 'main'
      - 'releases-**'
  pull_request:
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:

  ci-ubuntu-server:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        db:
          - sqlite
          - mysql
          - mariadb
          - postgres

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
      with:
        go-version-file: server/go.mod

    - name: "Test server: ${{matrix['db']}}"
      run: make server-test-${{matrix['db']}}

  ci-ubuntu-webapp:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        path: "focalboard"
        
    - name: npm ci
      run: cd focalboard/webapp && npm ci && cd -

    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
      with:
        go-version-file: focalboard/server/go.mod

    - name: Setup Node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
      with:
        node-version-file: focalboard/webapp/.nvmrc

    - name: Build Linux server
      run: cd focalboard; make server-linux-package

    - name: Copy server binary for Cypress
      run: cp focalboard/bin/linux/focalboard-server focalboard/bin/

    - name: Upload server package
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      with:
        name: focalboard-server-linux-amd64.tar.gz
        path: ${{ github.workspace }}/focalboard/dist/focalboard-server-linux-amd64.tar.gz

    - name: Lint & test webapp
      run: cd focalboard; make webapp-ci

  ci-windows-server:
    runs-on: windows-2022

    strategy:
      matrix:
        db:
          - sqlite

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        path: "focalboard"

    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
      with:
        go-version-file: focalboard/server/go.mod

    - name: "Test server (minimum): ${{matrix['db']}}"
      run: cd focalboard; make server-test-mini-${{matrix['db']}}

  ci-mac-server:
    runs-on: macos-15

    strategy:
      matrix:
        db:
          - sqlite

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        path: "focalboard"

    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
      with:
        go-version-file: focalboard/server/go.mod

    - name: "Test server (minimum): ${{matrix['db']}}"
      run: cd focalboard; make server-test-mini-${{matrix['db']}}
